/**
  * @file chisquare_mean.cpp
  * @brief File generated by tests/stats/chisquare_mean.py.
  */

/**
  * @test CHISQUARE.mean_scalar_df_3
  * @brief Verify stats::chisquare::mean matches scipy.stats.chi2.mean for mean_scalar_df_3
  */
TEST(CHISQUARE, mean_scalar_df_3)
{
    Tensor<float> k({1});
    k = 3.00000000000000000;

    Tensor<float> result = stats::chisquare::mean(k);

    Tensor<float> expected_result({1});
    expected_result = std::vector<float>{3.00000000000000000};

    EXPECT_NEAR(result[0], expected_result[0], 1e-06);
}

/**
  * @test CHISQUARE.mean_vector_dfs
  * @brief Verify stats::chisquare::mean matches scipy.stats.chi2.mean for mean_vector_dfs
  */
TEST(CHISQUARE, mean_vector_dfs)
{
    Tensor<float> k({4});
    k = std::vector<float>{1.00000000000000000, 2.00000000000000000, 3.00000000000000000, 4.00000000000000000};

    Tensor<float> result = stats::chisquare::mean(k);

    Tensor<float> expected_result({4});
    expected_result = std::vector<float>{1.00000000000000000, 2.00000000000000000, 3.00000000000000000, 4.00000000000000000};

    EXPECT_NEAR(result[0], expected_result[0], 1e-06);
    EXPECT_NEAR(result[1], expected_result[1], 1e-06);
    EXPECT_NEAR(result[2], expected_result[2], 1e-06);
    EXPECT_NEAR(result[3], expected_result[3], 1e-06);
}

/**
  * @test CHISQUARE.mean_vector_random_positive
  * @brief Verify stats::chisquare::mean matches scipy.stats.chi2.mean for mean_vector_random_positive
  */
TEST(CHISQUARE, mean_vector_random_positive)
{
    Tensor<float> k({6});
    k = std::vector<float>{0.42025453090147558, 1.19050674007124546, 1.62886149075446052, 1.47612136234190983, 0.40621759967896653, 0.42709566480983074};

    Tensor<float> result = stats::chisquare::mean(k);

    Tensor<float> expected_result({6});
    expected_result = std::vector<float>{0.42025453090147558, 1.19050674007124546, 1.62886149075446052, 1.47612136234190983, 0.40621759967896653, 0.42709566480983074};

    EXPECT_NEAR(result[0], expected_result[0], 1e-06);
    EXPECT_NEAR(result[1], expected_result[1], 1e-06);
    EXPECT_NEAR(result[2], expected_result[2], 1e-06);
    EXPECT_NEAR(result[3], expected_result[3], 1e-06);
    EXPECT_NEAR(result[4], expected_result[4], 1e-06);
    EXPECT_NEAR(result[5], expected_result[5], 1e-06);
}

/**
  * @test CHISQUARE.mean_matrix_2x3
  * @brief Verify stats::chisquare::mean matches scipy.stats.chi2.mean for mean_matrix_2x3
  */
TEST(CHISQUARE, mean_matrix_2x3)
{
    Tensor<float> k({2,3});
    k = std::vector<float>{0.50000000000000000, 1.00000000000000000, 2.00000000000000000, 3.00000000000000000, 4.00000000000000000, 5.00000000000000000};

    Tensor<float> result = stats::chisquare::mean(k);

    Tensor<float> expected_result({6});
    expected_result = std::vector<float>{0.50000000000000000, 1.00000000000000000, 2.00000000000000000, 3.00000000000000000, 4.00000000000000000, 5.00000000000000000};

    EXPECT_NEAR(result[0][0], expected_result[0], 1e-06);
    EXPECT_NEAR(result[0][1], expected_result[1], 1e-06);
    EXPECT_NEAR(result[0][2], expected_result[2], 1e-06);
    EXPECT_NEAR(result[1][0], expected_result[3], 1e-06);
    EXPECT_NEAR(result[1][1], expected_result[4], 1e-06);
    EXPECT_NEAR(result[1][2], expected_result[5], 1e-06);
}

/**
  * @test CHISQUARE.mean_view_with_weird_strides
  * @brief Ensure stats::chisquare::mean accepts non-contiguous/alias views for k and matches SciPy
  */
TEST(CHISQUARE, mean_view_with_weird_strides)
{
    Tensor<float> k_owner({6}, MemoryLocation::DEVICE);
    std::vector<float> k_owner_vals = {
        2.00000000000000000, 99.00000000000000000, 1.00000000000000000, 99.00000000000000000, 5.00000000000000000, 99.00000000000000000
    };
    k_owner = k_owner_vals;

    Tensor<float> k_alias(
        k_owner,
        std::vector<uint64_t>{0ull},
        std::vector<uint64_t>{3ull},
        std::vector<uint64_t>{2ull}
    );

    Tensor<float> result = stats::chisquare::mean(k_alias);

    Tensor<float> expected_result({3});
    expected_result = std::vector<float>{2.00000000000000000, 1.00000000000000000, 5.00000000000000000};

    EXPECT_NEAR(result[0], expected_result[0], 1e-06);
    EXPECT_NEAR(result[1], expected_result[1], 1e-06);
    EXPECT_NEAR(result[2], expected_result[2], 1e-06);
}
